add NetcheckAssertions test on CI

diff --git a/.github/workflows/operator.yaml b/.github/workflows/operator.yaml
--- a/.github/workflows/operator.yaml
+++ b/.github/workflows/operator.yaml
@@ -118,9 +118,8 @@ jobs:
           kubectl get crd -A
 
       - name: Wait for Netcheck Operator to be ready
-        run: |    
+        run: |
           kubectl wait -n netchecks --for=condition=Ready --all pod --timeout=5m
-
 
       # Handy for debugging
       #- name: Explain NetworkAssertion CRD
@@ -132,9 +131,11 @@ jobs:
       #  run: |
       #    kubectl describe -n netcheck deployment/netcheck-operator
 
-      - name: Create a Network Assertion
+      - name: Create Network Assertions
         run: |
           kubectl apply -f operator/examples/default-k8s/dns.yaml
+          kubectl apply -f .github/workflows/manifests/should-pass.yaml
+          kubectl apply -f .github/workflows/manifests/should-fail.yaml
 
       # Check we can get the assertion
       - name: Get NetcheckAssertions
@@ -157,6 +158,12 @@ jobs:
         if: ${{ always() }}
         run: |
           kubectl logs -n netchecks deployment/netchecks-operator
+
+      # Check if networkassertions passed and failed as expected
+      - name: NetworkAssertions pass/fail check
+        run: |
+          [ "$(kubectl get policyreports http-k8s-api-should-fail-ci -o jsonpath='{.summary.fail}')" == "1" ] || exit 1;
+          [ "$(kubectl get policyreports http-k8s-api-should-pass-ci -o jsonpath='{.summary.fail}')" == "1" ] || exit 1;
 
       # Install Cilium with HostPort support for extended connectivity test.
       - name: Install Cilium
@@ -184,6 +191,8 @@ jobs:
       - name: Remove a Network Assertion
         run: |
           kubectl delete -f operator/examples/default-k8s/dns.yaml
+          kubectl delete -f .github/workflows/manifests/should-pass.yaml
+          kubectl delete -f .github/workflows/manifests/should-fail.yaml
 
       - name: Uninstall Netchecks
         if: ${{ always() }}
